# Generated by Django 3.1.5 on 2021-01-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_memberprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
