# Generated by Django 3.1.5 on 2021-01-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=' ', max_length=100)),
                ('product_price', models.IntegerField(default=None)),
                ('brand_name', models.CharField(default=' ', max_length=100)),
                ('product_description', models.TextField(max_length=500, null=True)),
                ('available_stock', models.IntegerField(blank=True, default=0)),
                ('product_frontpage', models.ImageField(default='default.jpg', upload_to='product_frontpages')),
                ('product_number', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
