# Generated by Django 3.1.5 on 2021-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
