# Generated by Django 3.1.5 on 2021-02-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
