# Generated by Django 3.1.5 on 2021-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='quantity',
        ),
    ]
