# Generated by Django 3.1.5 on 2021-02-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210228_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profile',
        ),
        migrations.DeleteModel(
            name='OrderProfile',
        ),
    ]
