# Generated by Django 3.1.5 on 2021-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210228_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayurvedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=' ', max_length=100)),
                ('product_price', models.IntegerField(default=None)),
                ('brand_name', models.CharField(default=' ', max_length=100)),
                ('product_description', models.TextField(max_length=500, null=True)),
                ('available_stock', models.IntegerField(blank=True, default=0)),
                ('product_frontpage', models.ImageField(default='default.jpg', upload_to='product_frontpages')),
                ('categories', models.CharField(default=' ', max_length=30)),
                ('product_number', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
