# Generated by Django 3.1.5 on 2021-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_frontpage',
            field=models.ImageField(default='media/default.jpg', upload_to='product_frontpages'),
        ),
    ]
