# Generated by Django 3.1.5 on 2021-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210304_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_frontpage',
            field=models.ImageField(default='default.jpg', upload_to='product_frontpages'),
        ),
    ]
