# Generated by Django 3.1.5 on 2021-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210304_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayurvedic',
        ),
        migrations.AddField(
            model_name='item',
            name='type_of_item',
            field=models.IntegerField(default=None),
        ),
    ]
