# Generated by Django 3.1.5 on 2021-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210307_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_description',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
