# Generated by Django 3.1.5 on 2021-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
