# Generated by Django 3.1.5 on 2021-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210311_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
