# Generated by Django 3.1.5 on 2021-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210311_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
    ]
